import os, re, sys  # os:Finding .pgm files in a folder; re:For advanced string processing
from pathlib import Path  # For path operations
import numpy as np  # For numerical operations and arrays


# ---------- Natural sort key (e.g., v1_00092.pgm < v1_01683.pgm) ----------
def _natural_key(s: str):
    """Split a string into digit and non-digit chunks so numbers sort numerically."""
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', s)]


# ------ PGM I/O (supports P2 / P5) ---
def read_pgm(path: Path):
    """
    Read a PGM image as numpy array.
    Returns (img, maxval_from_header).
    """
    with open(path, 'rb') as f:
        magic = f.readline().strip()
        if magic not in (b'P2', b'P5'):
            raise ValueError(f'Not a PGM (P2/P5): {path}')

        def next_token():
            """
            Read the next non-comment, non-whitespace token from the file stream.
            PGM headers can include comments starting with '#'.
            """
            token = b''

            # Skip whitespace and full comment lines
            while True:
                c = f.read(1)
                if not c:
                    break
                if c == b'#':
                    f.readline()  # discard the rest of the comment line
                    continue
                if c.isspace():
                    continue
                token += c
                break

            # Read the rest of the token until whitespace
            while True:
                c = f.read(1)
                if not c or c.isspace():
                    break
                token += c
            return token

        width = int(next_token())
        height = int(next_token())
        maxval = int(next_token())

        if magic == b'P5':
            # Binary data: 1 byte per pixel if maxval < 256, otherwise 2 bytes.
            dtype = np.uint8 if maxval < 256 else np.uint16
            count = width * height
            bytes_per = 1 if dtype is np.uint8 else 2
            data = np.frombuffer(f.read(count * bytes_per), dtype=dtype, count=count)
            img = data.reshape((height, width))
        else:
            # ASCII data: read integers token by token.
            vals = []
            total = width * height
            while len(vals) < total:
                tok = next_token()
                if not tok:
                    break
                vals.append(int(tok))
            dtype = np.uint8 if maxval < 256 else np.uint16
            img = np.array(vals, dtype=dtype).reshape((height, width))

    return img, maxval


def write_p2_pgm(path: Path, img: np.ndarray, maxval: int | None = None):
    """
    Write a 2-D array to an ASCII PGM (P2).
    If maxval is None, use the image's maximum (falls back to 255 for empty arrays).
    """
    img = np.asarray(img)
    if maxval is None:
        maxval = int(img.max()) if img.size else 255

    h, w = img.shape
    with open(path, 'w', encoding='ascii') as f:
        f.write('P2\n# generated by extract_plane_effusion.py\n')
        f.write(f'{w} {h}\n{maxval}\n')
        # Write space-separated integers row by row.
        for row in img:
            f.write(' '.join(str(int(v)) for v in row) + '\n')


# ---------- Build a 3-D volume from a folder of PGM slices ----------
def stack_volume(folder: Path):
    """
    Load all *.pgm files from `folder`, natural-sort them, and stack into a
    3-D numpy array with shape (H, W, Z). Returns (volume, first_slice_max).
    """
    files = sorted([p for p in folder.glob('*.pgm')], key=lambda p: _natural_key(p.name))
    if not files:
        raise SystemExit(f'No .pgm in: {folder}')

    # Read the first slice to determine geometry and dtype
    first, maxval0 = read_pgm(files[0])
    H, W = first.shape
    dtype = first.dtype

    vol = np.empty((H, W, len(files)), dtype=dtype)  # volume[y, x, z]
    vol[..., 0] = first

    # Read remaining slices
    for k, p in enumerate(files[1:], start=1):
        img, mv = read_pgm(p)
        # If shape mismatch happens, you can enable this check:
        # if img.shape != (H, W):
        #     raise ValueError(f'Size mismatch at {p}: {img.shape} vs {(H, W)}')
        vol[..., k] = img
        # If maxval differs you can print a warning (usually not critical):
        # if mv != maxval0:
        #     print(f'Warning: maxval differs at {p}: {mv} vs {maxval0}', file=sys.stderr)

    return vol, int(first.max())


# ---------- Simple index parser ----------
def parse_index(s: str, length: int) -> int:
    """
    Convert an index string to an integer in [0, length-1].
    You can give an integer like '128'.
    Percentage like '50%' is also supported, but not necessary.
    """
    s = s.strip()
    if s.endswith('%'):
        r = float(s[:-1]) / 100.0
        r = min(max(r, 0.0), 1.0)
        idx = int(round(r * (length - 1)))
    else:
        idx = int(s)

    if not (0 <= idx < length):
        raise ValueError(f'index out of range: {idx} (len={length})')
    return idx


# ================== Ellipsoid effusion model (in CSF only) ==================
def add_ellipsoid_effusion(
    vis_vol: np.ndarray,
    label_vol: np.ndarray,
    csf_label: int,
    center: tuple,
    a: float,
    b: float,
    c: float,
    effusion_value: int = 100,
    roughness: float = 0.3,
    seed: int | None = None,
    angle_deg: float = 0.0
) -> np.ndarray:
    """
    Insert an irregular ellipsoidal effusion region into the volume.

    The effusion is restricted to voxels where label_vol == csf_label
    (i.e. CSF regions such as sulci / ventricles in the DHP).
    """
    H, W, Z = vis_vol.shape
    cy, cx, cz = center

    out = vis_vol
    csf_mask = (label_vol == csf_label)| (label_vol == 1)

    theta = np.deg2rad(angle_deg)
    cos_t = np.cos(theta)
    sin_t = np.sin(theta)

    # --- FIXED BOUNDARY: use same radius in y and x ---
    r_xy = int(np.ceil(max(a, b)))

    y_min = max(0, cy - r_xy)
    y_max = min(H, cy + r_xy + 1)
    x_min = max(0, cx - r_xy)
    x_max = min(W, cx + r_xy + 1)

    z_min = max(0, int(cz - c))
    z_max = min(Z, int(cz + c) + 1)
    # ---------------------------------------------------

    rng = np.random.default_rng(seed)
    shell_max = 1.5

    for y in range(y_min, y_max):
        for x in range(x_min, x_max):
            dy0 = float(y - cy)
            dx0 = float(x - cx)

            # Rotate in the xy-plane
            yr =  dy0 * cos_t + dx0 * sin_t
            xr = -dy0 * sin_t + dx0 * cos_t

            y_norm = yr / a
            x_norm = xr / b

            for z in range(z_min, z_max):
                dz0 = float(z - cz)
                z_norm = dz0 / c

                val = y_norm*y_norm + x_norm*x_norm + z_norm*z_norm

                inside = False
                if val <= 1.0:
                    inside = True
                elif val <= shell_max:
                    jitter = rng.uniform(0.0, roughness)
                    if val <= 1.0 + jitter:
                        inside = True

                #  Only modify CSF voxels
                if inside and csf_mask[y, x, z]:
                    out[y, x, z] = effusion_value

    return out


# ---------- Main: effusion + extract plane and save ----------
def main():
    import argparse
    ap = argparse.ArgumentParser(
        description='Extract a plane from a PGM volume, with ellipsoid effusion (CSF only).'
    )
    ap.add_argument('--folder', required=True, help='Folder containing axial .pgm slices')
    ap.add_argument('--plane', required=True,
                    choices=['x', 'y', 'z', 'sagittal', 'coronal', 'axial'],
                    help='Plane to extract: x/y/z or sagittal/coronal/axial')
    ap.add_argument('--index', required=True,
                    help='Index along chosen axis, e.g., 128 (integer)')
    ap.add_argument('--out', required=True, help='Output PGM path (P2 ASCII)')

    # Effusion centre and size parameters
    ap.add_argument('--effusion_y', type=int, default=None,
                    help='Effusion centre y index (0..H-1). If not given, use H//2.')
    ap.add_argument('--effusion_x', type=int, default=None,
                    help='Effusion centre x index (0..W-1). If not given, use W//2.')
    ap.add_argument('--effusion_z', type=int, default=None,
                    help='Effusion centre z index (0..Z-1). If not given, use Z//2.')
    ap.add_argument('--a', type=float, default=20.0,
                    help='Ellipsoid radius in y-direction (default 20).')
    ap.add_argument('--b', type=float, default=15.0,
                    help='Ellipsoid radius in x-direction (default 15).')
    ap.add_argument('--c', type=float, default=10.0,
                    help='Ellipsoid radius in z-direction (default 10).')
    ap.add_argument('--effusion_value', type=int, default=100,
                    help='Effusion brightness value (default 100).')

    args = ap.parse_args()

    folder = Path(args.folder)
    labels, _ = stack_volume(folder)  # labels shape: (H, W, Z) with tissue IDs

    H, W, Z = labels.shape

    # Start display volume from labels (no baseline enhancement)
    vis = labels.copy()

    # Decide effusion centre
    cy = args.effusion_y if args.effusion_y is not None else H // 2
    cx = args.effusion_x if args.effusion_x is not None else W // 2
    cz = args.effusion_z if args.effusion_z is not None else Z // 2

    # Clip to valid range
    cy = max(0, min(H - 1, cy))
    cx = max(0, min(W - 1, cx))
    cz = max(0, min(Z - 1, cz))

    csf_label = 14  # cerebrospinalfluid label in original DHP

    # Add ellipsoid effusion on display volume
    # 1st blob
    add_ellipsoid_effusion(
        vis, labels, csf_label,
        center=(cy, cx, cz),
        a=args.a, b=args.b, c=args.c,
        effusion_value=args.effusion_value,
        roughness=0.2, seed=1, angle_deg=90#90
    )

 #   # 2nd blob
    add_ellipsoid_effusion(
        vis, labels, csf_label,
        center=(310, 200, cz),
        a=180, b=30, c=1,
        effusion_value=args.effusion_value,
        roughness=0.2, seed=2, angle_deg=90.0#35
    )

    # 3rd blob
    add_ellipsoid_effusion(
        vis, labels, csf_label,
        center=(245, 200, cz),
        a=180, b=18, c=1,
        effusion_value=args.effusion_value,
        roughness=0.25, seed=3, angle_deg=0
    )

    plane = args.plane.lower()

    if plane in ('sagittal', 'x'):
        # Fix x, take a Y-Z plane. Transpose so Z is horizontal for intuitive viewing.
        x0 = parse_index(args.index, W)
        out = vis[:, x0, :].T           # (Z, H)

    elif plane in ('coronal', 'y'):
        # Fix y, take an X-Z plane. Transpose so Z is horizontal.
        y0 = parse_index(args.index, H)
        out = vis[y0, :, :].T           # (Z, W)

    else:
        # Axial (z): fix z, take an X-Y plane.
        z0 = parse_index(args.index, Z)
        out = vis[:, :, z0]             # (H, W)

    # Use the true max of the output slice for the PGM header (avoid maxval=0 issues).
    mx_out = int(out.max()) if out.size else 1
    write_p2_pgm(Path(args.out), out, maxval=mx_out)
    print(f"Saved: {args.out}")


if __name__ == '__main__':
    main()
