import os, re, sys  # os:Finding .pgm files in a folder; re:For advanced string processing
from pathlib import Path  # For path operations
import numpy as np        # For numerical operations and arrays


# ---------- Natural sort key (e.g., v1_00092.pgm < v1_01683.pgm) ----------
def _natural_key(s: str):
    """Split a string into digit and non-digit chunks so numbers sort numerically."""
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', s)]


# ------ PGM I/O (supports P2 / P5) ---
def read_pgm(path: Path):
    """
    Read a PGM image as numpy array.
    Returns (img, maxval_from_header).
    """
    with open(path, 'rb') as f:
        magic = f.readline().strip()
        if magic not in (b'P2', b'P5'):
            raise ValueError(f'Not a PGM (P2/P5): {path}')

        def next_token():
            """
            Read the next non-comment, non-whitespace token from the file stream.
            PGM headers can include comments starting with '#'.
            """
            token = b''

            # Skip whitespace and full comment lines
            while True:
                c = f.read(1)
                if not c:
                    break
                if c == b'#':
                    f.readline()  # discard the rest of the comment line
                    continue
                if c.isspace():
                    continue
                token += c
                break

            # Read the rest of the token until whitespace
            while True:
                c = f.read(1)
                if not c or c.isspace():
                    break
                token += c
            return token

        width = int(next_token())
        height = int(next_token())
        maxval = int(next_token())

        if magic == b'P5':
            # Binary data: 1 byte per pixel if maxval < 256, otherwise 2 bytes.
            dtype = np.uint8 if maxval < 256 else np.uint16
            count = width * height
            bytes_per = 1 if dtype is np.uint8 else 2
            data = np.frombuffer(f.read(count * bytes_per), dtype=dtype, count=count)
            img = data.reshape((height, width))
        else:
            # ASCII data: read integers token by token.
            vals = []
            total = width * height
            while len(vals) < total:
                tok = next_token()
                if not tok:
                    break
                vals.append(int(tok))
            dtype = np.uint8 if maxval < 256 else np.uint16
            img = np.array(vals, dtype=dtype).reshape((height, width))

    return img, maxval


def write_p2_pgm(path: Path, img: np.ndarray, maxval: int | None = None):
    """
    Write a 2-D array to an ASCII PGM (P2).
    If maxval is None, use the image's maximum (falls back to 255 for empty arrays).
    """
    img = np.asarray(img)
    if maxval is None:
        maxval = int(img.max()) if img.size else 255

    h, w = img.shape
    with open(path, 'w', encoding='ascii') as f:
        f.write('P2\n# generated by extract_plane_moderate_microh.py\n')
        f.write(f'{w} {h}\n{maxval}\n')
        # Write space-separated integers row by row.
        for row in img:
            f.write(' '.join(str(int(v)) for v in row) + '\n')


# ---------- Build a 3-D volume from a folder of PGM slices ----------
def stack_volume(folder: Path):
    """
    Load all *.pgm files from folder, natural-sort them, and stack into a
    3-D numpy array with shape (H, W, Z). Returns (volume, first_slice_max).
    """
    files = sorted([p for p in folder.glob('*.pgm')],
                   key=lambda p: _natural_key(p.name))
    if not files:
        raise SystemExit(f'No .pgm in: {folder}')

    # Read the first slice to determine geometry and dtype
    first, maxval0 = read_pgm(files[0])
    H, W = first.shape
    dtype = first.dtype

    vol = np.empty((H, W, len(files)), dtype=dtype)  # volume[y, x, z]
    vol[..., 0] = first

    # Read remaining slices
    for k, p in enumerate(files[1:], start=1):
        img, mv = read_pgm(p)
        # If shape mismatch happens, you can enable this check:
        # if img.shape != (H, W):
        #     raise ValueError(f'Size mismatch at {p}: {img.shape} vs {(H, W)}')
        vol[..., k] = img
        # If maxval differs you can print a warning (usually not critical):
        # if mv != maxval0:
        #     print(f'Warning: maxval differs at {p}: {mv} vs {maxval0}', file=sys.stderr)

    return vol, int(first.max())


# ---------- Simple index parser ----------
def parse_index(s: str, length: int) -> int:
    """
    Convert an index string to an integer in [0, length-1].
    You can give an integer like '128'. Percentage like '50%' is also supported,
    but not necessary.
    """
    s = s.strip()
    if s.endswith('%'):
        r = float(s[:-1]) / 100.0
        r = min(max(r, 0.0), 1.0)
        idx = int(round(r * (length - 1)))
    else:
        idx = int(s)

    if not (0 <= idx < length):
        raise ValueError(f'index out of range: {idx} (len={length})')
    return idx


# ================== White-matter mask + spherical microbleed ==================
def make_white_matter_mask(vol: np.ndarray, wm_label: int = 2) -> np.ndarray:
    """
    Make a white matter mask from the label volume.
    Assumes 'wm_label' is the ID of white matter in the original DHP labels.
    """
    return (vol == wm_label)


def add_spherical_microbleed(
    vis_vol: np.ndarray,
    label_vol: np.ndarray,
    wm_label: int,
    center: tuple,
    radius: int,
    wm_display_value: int = 28,  # kept for consistency, not used here
    lesion_value: int = 17,
) -> np.ndarray:
    """
    Draw ONE spherical hemorrhage inside white matter on vis_vol (in-place).

    - vis_vol: 3-D display volume (modified in-place).
    - label_vol: original label volume (to know where white matter is: label == wm_label).
    - wm_label: white matter label ID in the label volume (e.g. 2).
    - center: (cy, cx, cz) voxel indices.
    - radius: sphere radius in voxels.
    - lesion_value: intensity used for the hemorrhage (e.g. 17, darker than WM).
    """
    H, W, Z = vis_vol.shape
    cy, cx, cz = center

    wm_mask = (label_vol == wm_label)

    y_min = max(0, cy - radius)
    y_max = min(H, cy + radius + 1)
    x_min = max(0, cx - radius)
    x_max = min(W, cx + radius + 1)
    z_min = max(0, cz - radius)
    z_max = min(Z, cz + radius + 1)

    for y in range(y_min, y_max):
        for x in range(x_min, x_max):
            for z in range(z_min, z_max):
                if not wm_mask[y, x, z]:
                    continue  # only inside white matter
                dy = y - cy
                dx = x - cx
                dz = z - cz
                if dy * dy + dx * dx + dz * dz <= radius * radius:
                    vis_vol[y, x, z] = lesion_value

    return vis_vol


# ---------- MODERATE: generate several centres around one user point ----------
def generate_moderate_centers(cy: int, cx: int, cz: int, H: int, W: int, Z: int):
    lesions = [
        (0,   0,   1),
        (6,   2,   2),   # mian lesion,radius=2
        (1,   6,   1),
        (-4,   9,   1),
        (-6,   12,   2),
        (10,   -7,   1),
        (8,   -7,   2),
        (-8,   -7,   1),
        (-4,-4,1),
        (10,10,1),
        (-6,-6,1),
    ]

    centers = []
    for dy, dx, rr in lesions:
        yy = min(max(cy + dy, 0), H - 1)
        xx = min(max(cx + dx, 0), W - 1)
        centers.append((yy, xx, cz, rr))
    return centers


# ---------- Main: extract plane and save ----------
def main():
    import argparse
    ap = argparse.ArgumentParser(
        description='Extract a plane from a PGM volume, with MODERATE microbleeds.'
    )
    ap.add_argument('--folder', required=True,
                    help='Folder containing axial .pgm slices')
    ap.add_argument('--plane', required=True,
                    choices=['x', 'y', 'z', 'sagittal', 'coronal', 'axial'],
                    help='Plane to extract: x/y/z or sagittal/coronal/axial')
    ap.add_argument('--index', required=True,
                    help='Index along chosen axis, e.g., 128 (integer)')
    ap.add_argument('--out', required=True,
                    help='Output PGM path (P2 ASCII)')

    # Same interactive options as before – one centre from the user
    ap.add_argument('--lesion_y', type=int, default=None,
                    help='Lesion centre y index (0..H-1). If not given, use H//2.')
    ap.add_argument('--lesion_x', type=int, default=None,
                    help='Lesion centre x index (0..W-1). If not given, use W//2.')
    ap.add_argument('--lesion_z', type=int, default=None,
                    help='Lesion centre z index (0..Z-1). If not given, use Z//2.')
    ap.add_argument('--radius', type=int, default=5,
                    help='Lesion radius in voxels (default 5).')

    args = ap.parse_args()

    folder = Path(args.folder)
    labels, _ = stack_volume(folder)   # labels shape: (H, W, Z)
    H, W, Z = labels.shape

    # Prepare display volume (start from labels; then remap white matter)
    vis = labels.copy()

    # White matter label in the original DHP (from tissueorder: 2 = whitematter)
    wm_label = 2

    # Display values: 28 for white matter, 17 for hemorrhage
    wm_display_value = 28
    lesion_value = 17

    # ---- brighten all white matter ONCE for display ----
    wm_mask = (labels == wm_label)
    vis[wm_mask] = wm_display_value
    # ----------------------------------------------------
   


    # Decide lesion centre (if user did not give, use centre of the volume)
    cy = args.lesion_y if args.lesion_y is not None else H // 2
    cx = args.lesion_x if args.lesion_x is not None else W // 2
    cz = args.lesion_z if args.lesion_z is not None else Z // 2

    # Keep indices inside bounds
    cy = max(0, min(H - 1, cy))
    cx = max(0, min(W - 1, cx))
    cz = max(0, min(Z - 1, cz))

    # ============ MODERATE: create several microbleeds around the centre ============
    centers = generate_moderate_centers(cy, cx, cz, H, W, Z)

    vis_mod = vis
    for (yy, xx, zz, rr) in centers:
        vis_mod = add_spherical_microbleed(
        vis_vol=vis_mod,
        label_vol=labels,
        wm_label=wm_label,
        center=(yy, xx, zz),
        radius=rr,
        wm_display_value=wm_display_value,
        lesion_value=lesion_value,
    )
    # ===============================================================================

    plane = args.plane.lower()

    if plane in ('sagittal', 'x'):
        # Fix x, take a Y-Z plane. Transpose so Z is horizontal for intuitive viewing.
        x0 = parse_index(args.index, W)
        out = vis_mod[:, x0, :].T           # (Z, H)

    elif plane in ('coronal', 'y'):
        # Fix y, take an X-Z plane. Transpose so Z is horizontal.
        y0 = parse_index(args.index, H)
        out = vis_mod[y0, :, :].T           # (Z, W)

    else:
        # Axial (z): fix z, take an X-Y plane.
        z0 = parse_index(args.index, Z)
        out = vis_mod[:, :, z0]             # (H, W)

    # Use the true max of the output slice for the PGM header (avoid maxval=0 issues).
    mx_out = int(out.max()) if out.size else 1
    write_p2_pgm(Path(args.out), out, maxval=mx_out)
    print(f"Saved: {args.out}")


if __name__ == '__main__':
    main()
